commands:
  discord:
    aliases:
      - "ds"
    lines:
      - "&7$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
      - "&7$ &9&lDiscord: &bhttps://discord.gg/pXABrx68hK    $"
      - "&7$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
  test-cmd:
    aliases:
      - "test-cmd1"
    lines:
      - "Hello world!"