name: EasyTxtCommands
version: '${project.version}'
main: com.github.sintcraft.easytxtcommands.EasyTxtCommands
api-version: 1.19
depend: [ CommandAPI ]
authors: [ sintcraft ]
description: A Minecraft plugin to place commands easily and simply so that players only receive a message with useful information.
